var annotated_dup =
[
    [ "amuse", null, [
      [ "ADSR", "structamuse_1_1_a_d_s_r.html", "structamuse_1_1_a_d_s_r" ],
      [ "ADSRDLS", "structamuse_1_1_a_d_s_r_d_l_s.html", "structamuse_1_1_a_d_s_r_d_l_s" ],
      [ "AudioGroup", "classamuse_1_1_audio_group.html", "classamuse_1_1_audio_group" ],
      [ "AudioGroupData", "classamuse_1_1_audio_group_data.html", "classamuse_1_1_audio_group_data" ],
      [ "AudioGroupIndex", "structamuse_1_1_audio_group_index.html", "structamuse_1_1_audio_group_index" ],
      [ "AudioGroupPool", "classamuse_1_1_audio_group_pool.html", "classamuse_1_1_audio_group_pool" ],
      [ "AudioGroupProject", "classamuse_1_1_audio_group_project.html", "classamuse_1_1_audio_group_project" ],
      [ "AudioGroupSampleDirectory", "classamuse_1_1_audio_group_sample_directory.html", "classamuse_1_1_audio_group_sample_directory" ],
      [ "BooBackendSubmix", "classamuse_1_1_boo_backend_submix.html", "classamuse_1_1_boo_backend_submix" ],
      [ "BooBackendVoice", "classamuse_1_1_boo_backend_voice.html", "classamuse_1_1_boo_backend_voice" ],
      [ "BooBackendVoiceAllocator", "classamuse_1_1_boo_backend_voice_allocator.html", "classamuse_1_1_boo_backend_voice_allocator" ],
      [ "ChannelMap", "structamuse_1_1_channel_map.html", "structamuse_1_1_channel_map" ],
      [ "EffectBase", "classamuse_1_1_effect_base.html", "classamuse_1_1_effect_base" ],
      [ "EffectBaseTypeless", "classamuse_1_1_effect_base_typeless.html", "classamuse_1_1_effect_base_typeless" ],
      [ "EffectChorus", "classamuse_1_1_effect_chorus.html", "classamuse_1_1_effect_chorus" ],
      [ "EffectChorusImp", "classamuse_1_1_effect_chorus_imp.html", "classamuse_1_1_effect_chorus_imp" ],
      [ "EffectDelay", "classamuse_1_1_effect_delay.html", "classamuse_1_1_effect_delay" ],
      [ "EffectDelayImp", "classamuse_1_1_effect_delay_imp.html", "classamuse_1_1_effect_delay_imp" ],
      [ "EffectReverbHi", "classamuse_1_1_effect_reverb_hi.html", "classamuse_1_1_effect_reverb_hi" ],
      [ "EffectReverbHiImp", "classamuse_1_1_effect_reverb_hi_imp.html", "classamuse_1_1_effect_reverb_hi_imp" ],
      [ "EffectReverbStd", "classamuse_1_1_effect_reverb_std.html", "classamuse_1_1_effect_reverb_std" ],
      [ "EffectReverbStdImp", "classamuse_1_1_effect_reverb_std_imp.html", "classamuse_1_1_effect_reverb_std_imp" ],
      [ "Emitter", "classamuse_1_1_emitter.html", "classamuse_1_1_emitter" ],
      [ "Engine", "classamuse_1_1_engine.html", "classamuse_1_1_engine" ],
      [ "Entity", "classamuse_1_1_entity.html", "classamuse_1_1_entity" ],
      [ "Envelope", "classamuse_1_1_envelope.html", "classamuse_1_1_envelope" ],
      [ "IBackendSubmix", "classamuse_1_1_i_backend_submix.html", "classamuse_1_1_i_backend_submix" ],
      [ "IBackendVoice", "classamuse_1_1_i_backend_voice.html", "classamuse_1_1_i_backend_voice" ],
      [ "IBackendVoiceAllocator", "classamuse_1_1_i_backend_voice_allocator.html", "classamuse_1_1_i_backend_voice_allocator" ],
      [ "IntrusiveAudioGroupData", "classamuse_1_1_intrusive_audio_group_data.html", "classamuse_1_1_intrusive_audio_group_data" ],
      [ "Keymap", "structamuse_1_1_keymap.html", "structamuse_1_1_keymap" ],
      [ "LayerMapping", "structamuse_1_1_layer_mapping.html", "structamuse_1_1_layer_mapping" ],
      [ "Listener", "classamuse_1_1_listener.html", null ],
      [ "ReverbDelayLine", "structamuse_1_1_reverb_delay_line.html", "structamuse_1_1_reverb_delay_line" ],
      [ "Sequencer", "classamuse_1_1_sequencer.html", "classamuse_1_1_sequencer" ],
      [ "SFXGroupIndex", "structamuse_1_1_s_f_x_group_index.html", "structamuse_1_1_s_f_x_group_index" ],
      [ "SongGroupIndex", "structamuse_1_1_song_group_index.html", "structamuse_1_1_song_group_index" ],
      [ "SongState", "classamuse_1_1_song_state.html", "classamuse_1_1_song_state" ],
      [ "SoundMacroState", "classamuse_1_1_sound_macro_state.html", "classamuse_1_1_sound_macro_state" ],
      [ "Submix", "classamuse_1_1_submix.html", "classamuse_1_1_submix" ],
      [ "SurroundProfiles", "classamuse_1_1_surround_profiles.html", null ],
      [ "Voice", "classamuse_1_1_voice.html", "classamuse_1_1_voice" ]
    ] ]
];